### ISSUE TITLE
Make it better

### ISSUE THREAD

**Issue by antonzaytsev** [krhorst/active_admin_importable#1]
Hello Kevin,

I know you did this gem only for your needs in some project, but if you want I can help you make it better, if you will maintain it in future I can add some features and send you pull request.
If you don't want maintain it in future, than I want you invite in my repository to help me from time to time.

What do you think ?

few ideas from my head:
1. Support import of csv, json and xml (all format active admin supports to export)
2. Add some option before import (force import, only listed fields and so on)
3. Add preview of import with ability to change fields
4. Anything else from you ?

Sorry if there are mistakes in text, my english is not native.

**Comment by Fivell** [comment]
Hi guys, I'm interested in new features too! AA rocks =)

**Comment by antonzaytsev** [comment]
Igor, feel free to fork and start to work on new features :)
Do you have ideas how to improve gem, what we can add?
May be need a list of features?

**Comment by krhorst** [comment]
Import is something I end up using a lot so I'm definitely interested in making it better. A few features I can think of:

More graceful error handling in general

Importing data with associations by a field on the associated model (i.e. while importing products, store_name will perform store.find_by_name and associate the product with that store)

Better handling of non-UTF8 characters (currently kills the import)

Some rspec test coverage

**Comment by antonzaytsev** [comment]
Ok one more detail, Kevin, are u ok to maintain it in future ? If so can you add me in you rep so I can add and manage features and commits? 
We need to add all above features as separate issues may be discuss some of them, but first will be good to decide where to do this.

Cheers!

**Comment by krhorst** [comment]
Hi Anton,

Yes, I'm up to maintain it. I just added you as a collaborator, look forward to building this out!

-Kevin

**Comment by antonzaytsev** [comment]
Awesome! Thank you!
Let's start from adding issues to do to see the whole picture of future versions
