### ISSUE TITLE
Importing data with associations by a field on the associated model

### ISSUE THREAD

**Issue by antonzaytsev** [krhorst/active_admin_importable#6]
Importing data with associations by a field on the associated model (i.e. while importing products, store_name will perform store.find_by_name and associate the product with that store)

**Comment by krhorst** [comment]
With the ability to pass a custom processing block in, we can now do this fairly easily (see the Custom Import section of the Readme). Do you think there is still much of a need for automatic import of associations, or can we go   ahead and close this one out as well?

**Comment by antonzaytsev** [comment]
I like this idea with code block which calling on each row. This issue can be closed now.
Thank you.
